language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.3
otp_release:
  - 17.5
  - 18.2.1
  - 19.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
# before_script:
#   - mix dialyzer.plt
# script:
#   - mix dialyzer --halt-exit-status
#   - mix test
