language: elixir
elixir:
  - 1.3.3
otp_release:
  - 19.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - mix credo --strict
before_script:
  - mix dialyzer.plt
script:
  - mix dialyzer --halt-exit-status
  - mix test
